### ISSUE TITLE
introduction on the discourse page

### ISSUE THREAD

**Issue by lheagy** [jupyterhub/team-compass#145]
The jupyter discourse was initiated for the JupyterHub and Binder communities, but following the team meeting in DC, I think it has grown in scope to include other aspects of Jupyter, including 
- [JupyterLab](https://discourse.jupyter.org/c/jupyterlab)
- [Enterprise Gateway](https://discourse.jupyter.org/c/enterprise-gateway)
- etc. 

So I think the text for the intro should be broadened to include the whole Jupyter community

![image](https://user-images.githubusercontent.com/6361812/55500493-4be69400-55fd-11e9-8fb4-51942c637611.png)

I am not sure where the best place to have the conversation on the language is? Also, I am guessing that only the admins can update the discourse intro text.

**Comment by consideRatio** [comment]
Oh is that our banner post? Here is a direct link to view it as a normal post: https://discourse.jupyter.org/t/welcome-to-the-jupyterhub-discourse-how-to-use-this-site/30

The banner post is the one shown in blue until dismissed, it should be shorter as it is displayed like that.

This post was actually made into a "WIKI Post". Those can be edited by everybody, and we have version control of the edit history etc. I like the WIKI post concept :D

![image](https://user-images.githubusercontent.com/3837114/55508717-bed22800-565a-11e9-883c-f3c44b8ab161.png)

# Action plan
- [ ] We create a new post and make it into a WIKI post (done: [here it is](https://discourse.jupyter.org/t/this-will-be-made-into-our-banner-post/700)) ...
- [ ] ... and edit that to be a new more suitable Banner post.
- [ ] ... and decide if we want to change something with the [current banner post](https://discourse.jupyter.org/t/welcome-to-the-jupyterhub-discourse-how-to-use-this-site/30) that will no longer been seen as a banner post, there can only be one.

**Comment by choldgraf** [comment]
I've edited both of those pages with a proposed update to the content - would love some feedback! I think we should change that banner ASAP so we're not confusing people when they arrive.

**Comment by consideRatio** [comment]
Thanks @choldgraf ! Done!
