### ISSUE TITLE
Releasing Z2JH

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#228]
@jupyterhub/jupyterhubteam I'd love to see a Z2JH release be made, so I'm reaching out for help to accomplish that. What's missing mostly is making releases of other dependent projects, so we can bump them in z2jh. If you have time to spare, I'd like your help to take these repositories towards a release!

## z2jh dependency release checklist

- [x] [jupyterhub/configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy)
  - [x] Update CHANGELOG.md https://github.com/jupyterhub/configurable-http-proxy/pull/221
  - [x] Add RELEASE.md https://github.com/jupyterhub/configurable-http-proxy/pull/220
- [x] [jupyterhub/jupyterhub](https://github.com/jupyterhub/jupyterhub)
  There are many fixes available in JupyterHub master since last release, for z2jh one big is relating to stability on startup during simultaneous hub and proxy upgrades.
  - [x] Update docs/source/changelog.md https://github.com/jupyterhub/jupyterhub/pull/2830
  - [x] Add RELEASE.md ([CHECKLIST-Release.md](https://github.com/jupyterhub/jupyterhub/blob/master/CHECKLIST-Release.md))
  - [x] Get the docs update merged before JH release https://github.com/jupyterhub/jupyterhub/pull/2820
- [x] [jupyterhub/oauthenticator](https://github.com/jupyterhub/oauthenticator)
  It is required for GitLab authentication fix that GitLab themselves would like to see included in Z2JH. They have made one click install of Z2JH in k8s clusters! I'm really eager to help them get this issue fixed.
  - [x] OK to release, we can always make more releases later https://github.com/jupyterhub/oauthenticator/issues/299
  - [x] Update CHANGELOG.md https://github.com/jupyterhub/oauthenticator/pull/308
  - [x] Add RELEASE.md https://github.com/jupyterhub/oauthenticator/pull/294
  - [x] Try making a release by pushing a git tag using @manics PyPI CD with TravisCI
  - [x] Updating RELEASE.md for automatic releases.
- [x] [jupyterhub/kubespawner](https://github.com/jupyterhub/kubespawner)
  It contains a bugfix for k8s 1.16 among other things.
  - [x] Review/Merge PR solving CI issues https://github.com/jupyterhub/kubespawner/pull/368
  - [x] Review/Decide on [a few PRs in need of review](https://github.com/jupyterhub/kubespawner/pulls?q=is%3Apr+is%3Aopen+label%3A%22needs+review%22)
  - [x] Update docs/source/changelog.rst https://github.com/jupyterhub/kubespawner/pull/372
  - [x] Add RELEASE.md https://github.com/jupyterhub/kubespawner/pull/376
  - [x] Attempt to deploy PyPI package with CD following a push of a git tag, suceeded, see [logs](https://travis-ci.org/jupyterhub/kubespawner/jobs/617972209)! Lesson learned that the test also run before. Perhaps we can tweak it so it becomes a pure deploy job without the test run also.
- [x] [jupyterhub/ltiauthenticator](https://github.com/jupyterhub/ltiauthenticator)
  - [x] Review / Merge [lots of required PRs fixing issues](https://github.com/jupyterhub/ltiauthenticator/pulls/consideratio) blocking its inclusion in z2jh's hub image.
  - [x] Make a release
  - [x] Reinstall it into the z2jh hub image, where it currently has been deactivated because it's malfunctioning.

## z2jh itself checklist
- [x] Make a changelog - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1503
- [x] Bump jupyterhub a final time to whatever master we got or if a recent release is made
- [x] Resolve https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1501
- [x] UPDATE: I don't consider this required for us to fix pre-release any more.
   Fix the core pod toleration bug - or feature, it is simply not added, that logic was stripped away from a past PR. Perhaps we don't need to fix this but it should at least be documented then.
  - [ ] Issue about it: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1486
- Add support for environment variables mounted from secrets that arn't simply a key value pair
  - [ ] Current status documentation PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1462
  - [ ] A discussion about it: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1103

**Comment by choldgraf** [comment]
I agree it would be fantastic to get a new release out. Perhaps we can post this issue on the community forum as well?

**Comment by consideRatio** [comment]
@betatim i've now updated tasks of relevance and put in some work myself already. @manics shall we try making a release. Inspecting the PR lists of the repositories and helping me verify that it makes sense to make a release in the current state is relevant help for example.

**Comment by choldgraf** [comment]
Just a quick thought from me: it would be awesome if we could get the new documentation PR merged in `/jupyterhub` before a new release is made, since the documentation there is for `stable/` by default, not `latest/`

**Comment by consideRatio** [comment]
Attention specifically to:
- KubeSpawner PRs in need of review and/or decisions: https://github.com/jupyterhub/kubespawner/pulls?q=is%3Apr+is%3Aopen+label%3A%22needs+review%22
- OAuthenticator PRs in need of review and/or decisions: https://github.com/jupyterhub/oauthenticator/pulls?q=is%3Apr+is%3Aopen+label%3A%22needs+review%22

**Comment by consideRatio** [comment]
I've made a release of oauthenticator now, and up comes kubespawner, and then we have jupyterhub itself left!

**Comment by consideRatio** [comment]
Review help request:
- https://github.com/jupyterhub/kubespawner/pull/376
- https://github.com/jupyterhub/kubespawner/pull/377

I'll go ahead and release kubespawner after this using the @manics setup pattern to do PyPI CD by pushing a git tag.

It almost worked with oauthenticator, next try is with kubespawner :)

**Comment by consideRatio** [comment]
Kubespawner is now released and I got Z2JH to work on k8s 1.16, and I submitted PRs to fix binderhub for k8s 1.16 as well. See https://github.com/jupyterhub/binderhub/pull/1012 and https://github.com/jupyterhub/binderhub/pull/1013.

**Comment by consideRatio** [comment]
Prio to resolve: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1501

**Comment by consideRatio** [comment]
A jupyterhub release would be nice to reference, but nothing that should stop us from releasing alpha/beta of z2jh using current master instead. Most things have come around now.

**Comment by mjuric** [comment]
Apologies if this has an obvious answer, but does one of the recent alpha releases include the kubespawner with the https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1501 fix?

(more generally, is there a way to quickly see which commits/releases went into each `alpha`-series Helm chart + hub images)?

**Comment by consideRatio** [comment]
No obvious answer, yepp the latest does for example!

We dont have a way to track dependencies for chart releases yet :/ it would be nice to have some pip freeze or similar provided someplace.

**Comment by consideRatio** [comment]
@mjuric you correctly identified a bug, it is resolved by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1518.

---

I also identified issues with the ltiauthenticator that needs to be solved, I made a few PRs to do so to the best of my ability, but there is one commit in https://github.com/jupyterhub/ltiauthenticator/pull/26 that require a review by someone with more background understanding about the code base.

**Comment by consideRatio** [comment]
jupyterhub/litauthenticator issues resolved!

**Comment by consideRatio** [comment]
I'd be fine making a beta-release of z2jh - should we make it reference a jupyterhub beta release first or not?

**Comment by manics** [comment]
If the final z2jh release will include a new jupyterhub release I think it makes sense to tag a jupyterhub beta too and include it in the Z2JH beta, so that it gets some testing.

**Comment by consideRatio** [comment]
Z2JH 0.9.0 released :sunflower:

**Comment by consideRatio** [comment]
Upgrade instructions / changelog: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#090---2020-04-15

**Comment by choldgraf** [comment]
![image](https://user-images.githubusercontent.com/1839645/79375345-507ea180-7f0d-11ea-8360-4f412978fd04.png)
