### ISSUE TITLE
Write a report for our EOSS grant

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#367]
# Background

We need to write a report for our CZI EOSS grant that we used throughout 2019 (we actually have an extension for a little bit of extra money left over at the end, but we need to fill a report now either way). Can @betatim and @GeorgianaElena help me write this report? It basically requires that we talk a little bit about the work that's been done over the past year across the community.

- Due date: February 15th
- Draft document: [Link to Google Doc](https://docs.google.com/document/d/1zbo2J_m13FEvKaqNuVf5aYiAgpCEctfo3dCWKmVIBKA/edit#)

# ToDo

- [x] Take a look at the questions we need to answer
- [x] Outline some general things to put in each section (e.g. deliverables, or notable things we did). @GeorgianaElena and @betatim can you help by writing down things that reflect your work in 2019
- [x] Convert into "narrative" text that reads better
- [x] Submit

**Comment by choldgraf** [comment]
**Update**: I've requested an extension to February 15th and it was approved. So we need to submit the report by then.

I've got the financial report from NumFocus so we just need to put together a 2 page short report about the work that was done.

Here are some bullet items that we can include in the report. @betatim and @GeorgianaElena can you please add any below that you think are relevant? It would really really help me in putting together this report.

> - Key Outcomes
> - Summary of problems encountered during the grant period and steps to overcome including any changes in the research plan.
> - Description of the results and deliverables of the work done under this grant to date ([see here for a link to the deliverables we put on the grant](https://docs.google.com/document/d/1zbo2J_m13FEvKaqNuVf5aYiAgpCEctfo3dCWKmVIBKA/edit#heading=h.i5ppqmqqiiwa))
> - All software code, datasets, protocols, and reagents developed and links to publicly available repository/repositories (include accession numbers or similar where appropriate)
>   - I think that this can include any significant changes in any JupyterHub project that @GeorgianaElena or @betatim helped usher in while "on grant time"
> - Links to all presentations with reference

**Comment by choldgraf** [comment]
Hey all - I took some copy from what @GeorgianaElena sent me, and drafted a grant report here:

https://docs.google.com/document/d/1zbo2J_m13FEvKaqNuVf5aYiAgpCEctfo3dCWKmVIBKA/edit#

Would love any feedback from folks. I'll plan to submit on the 15th.

**Comment by choldgraf** [comment]
I've just submitted this report! Many thanks @manics for taking a look :-)
