### ISSUE TITLE
Z2JH 1.0.0-beta.1 release sprint - a few action points

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#416]
These are open PRs and action points I'd love help with for a Z2JH release:
- [x] jupyterhub/zero-to-jupyterhub-k8s#2211 (review, merge)
- [x] jupyterhub/zero-to-jupyterhub-k8s#2224 (review, merge)
- [x] jupyterhub/zero-to-jupyterhub-k8s#2226 (review, feel free to push suggestions directly, merge)
- [x] jupyterhub/zero-to-jupyterhub-k8s/pull/2175 (review, I'll make a final update, review, merge)

**Comment by consideRatio** [comment]
Done!
