### ISSUE TITLE
Give a talk about the JupyterHub DEI grant at the CZI meeting

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#455]
### Description

We've been asked to give a brief talk about the JupyterHub DEI EOSS grant at the upcoming CZI meeting on November 3rd. Here's the relevant bit from an email I just received:

> We would like to invite you to give a 2 minute overview of your supplemental project focused on Diversity and Inclusion on Day 2 (Wednesday, November 3). Please confirm your acceptance by responding to this email.
> 
> 
> Format and timing
> 
> 
> Please pre-record your two minute overview of your project and goals. You will be one of 14 presentations, presented from 10:30 am-12:45 pm PT. After the project presentations, we will moderate a panel discussion about diversifying the contributor pipeline for open source software projects in biomedical research. 

I spoke with @sgibson91 and she mentioned that the panel time is a bit late, so she'll record the video, and I can sit on the panel.

### Tasks

- [x] Record the 2-minute overview video before November 1st. (@sgibson91)
- [x] Send to @choldgraf to upload (or ask @choldgraf for the upload link)
- [x] @choldgraf sits on the panel

**Comment by choldgraf** [comment]
Some more updates from the CZI team that were just sent to me, copying here so @sgibson91 knows about the formatting stuff:

---

In case you have not, please keep this in mind when recording your video:

- The video should be submitted in a .mp4 format. 
- The submitted video should be 16:9 (widescreen) format, not 4:3
- If you are using Zoom's record feature to create the video, be mindful not to use the shared window format as this often stretches the screen and creates additional black bars on each side of the screen. Shared Screen with speaker thumbnail should be ok, but please verify the 16:9 aspect ratio! (see below for other tips on recording with Zoom)
- Please try to submit your video in advance so that we may follow up in case there are audio/visual/formatting issues.

### Format and timing

Please pre-record your two minute overview of your project and goals. You will be one of 14 presentations, presented from 10:30 am-12:45 pm PT. After the project presentations, we will moderate a panel discussion about diversifying the contributor pipeline for open source software projects in biomedical research. 

Below are instructions on recording your video on Zoom:

Step 1: Start a meeting as the host.
Step 2: As soon as the meeting starts, click on the "Record" button in the Zoom toolbar
Step 3: Click on "Record to the Cloud" or "Record to this computer" to begin the process of recording the meeting.
Step 4: If you would like to stop the recording, click on the "Pause/Stop Recording" or click on "End Meeting".
Step 5: Save and rename the recording file with your name and upload the video onto this folder

**Comment by sgibson91** [comment]
Closing this now as the CZI EOSS meeting wrapped up yesterday 🚀

**Comment by choldgraf** [comment]
Yahoo - thanks @sgibson91 for recording the two-minute presentation!
