### ISSUE TITLE
Contract Changeset consulting to provide support to Sarah in her CSL role

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#641]
We've decided to work with an open source consultancy to provide strategic guidance to @sgibson91 in her role as Community Strategic Lead for our EOSS grant. Our goal is to provide Sarah feedback and ideas for how to carry out this role well, both from a personal and from a project perspective. We'll work with [Changeset Consulting](https://www.changeset.nyc/), which is led by Sumana Harihareswara - someone with a lot of experience across the open source / Python ecosystems.

The cost will be ~$7,000 for around 30 hours of consulting work on the grant.

This is an issue to track setting up the contract, and for transparency with others on the team.

### Tasks

- [x] Initial meeting with Sumana and Sarah to discuss ideas
- [x] Agree to move forward
- [x] Set up contract with NumFocus

**Comment by choldgraf** [comment]
### Current status: waiting to hear back from NumFocus

I've asked NumFocus how to set up this contract with them, so will update this when I hear back from them.

**Comment by choldgraf** [comment]
This contract is now set up after another month of waiting to hear from NumFocus and finally hounding them into setting up the contract.
