### ISSUE TITLE
Overview of release planning

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#650]
With JupyterHub 4 released, the distributions z2jh and tljh benefits from a release as well, and when they are to make a breaking release I figure its also nice to have up to date versions of other projects they depend on, such as kubespawner, oauthenticator, etc.

### Tracked major version releases

- [x] JupyterHub 4 - https://github.com/jupyterhub/jupyterhub/issues/4350
- [x] oauthenticator 16 - https://github.com/jupyterhub/oauthenticator/issues/585
  - I'd like to wait for this in z2jh and tljh because it includes notable breaking changes i want to be part of z2jh/tljh's next major version release
  - Pending completion of https://github.com/jupyterhub/oauthenticator/pull/594
- [x] z2jh 3 (beta.2 is out, nothing planned before 3.0.0)- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3091
  - [x] KubeSpawner 5 - https://github.com/jupyterhub/kubespawner/issues/717
  - [x] KubeSpawner 6 - https://github.com/jupyterhub/kubespawner/issues/732
- [x] tljh 1 (1.0.0b1 is planned) - https://github.com/jupyterhub/the-littlest-jupyterhub/issues/873
  - [x] systemdspawner 1.0.0 - https://github.com/jupyterhub/systemdspawner/issues/109
  - [x] traefik-proxy 1.0.0 - https://github.com/jupyterhub/traefik-proxy/pull/205
- [ ] BinderHub 1 - https://github.com/jupyterhub/binderhub/issues/1667
  - [ ] docker-image-cleaner 1.0.0 - https://github.com/jupyterhub/docker-image-cleaner/issues/125
  - [x] z2jh 3.0.0
- [x] jupyter-server-proxy 4 - https://github.com/jupyterhub/jupyter-server-proxy/issues/388
- [x] simpervisor 1 - https://github.com/jupyterhub/simpervisor/issues/32
- [x] tmpauthenticator 1.0.0 -  https://github.com/jupyterhub/tmpauthenticator/issues/30
- [ ] ldapauthenticator 1.3.3/1.4.0/2.0.0 - https://github.com/jupyterhub/ldapauthenticator/issues/220

### Tracked minor/patch version releases

- [x] nativeauthenticator 1.2.0 - https://github.com/jupyterhub/nativeauthenticator/issues/241
- [x] configurable-http-proxy 4.5.5 - https://github.com/jupyterhub/configurable-http-proxy/pull/472
- [x] jupyter-remote-desktop-proxy - https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/41

**Comment by minrk** [comment]
I haven't been on top of the oauthenticator 16 plans, but I trust you and this sounds fine to me. Preparing to release one thing shouldn't in general put too much pressure on upstream or downstream packages to release.

**Comment by krassowski** [comment]
Are there plans for cutting a new 4.0.x anytime soon? It looks like a number of backports (some more exciting than others) have landed since 4.0.2 :)

**Comment by minrk** [comment]
Yes, those backports are in preparation for 4.1 soon. I'm working on one remaining issue before cutting the release.

**Comment by consideRatio** [comment]
JupyterHub 4.1.0, oauthenticator 16.3.0, and z2jh 3.3.0 was released today

**Comment by consideRatio** [comment]
Closing as resolved
